language: rust
cache: cargo
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo clippy -- -W clippy::nursery -W clippy::pedantic -W clippy::cargo
        - cargo build --verbose
        - cargo fmt -- --check
    fast_finish: true
    allow_failures:
      - rust: nightly
