[package]
name = "i3lockr"
description = "Distort a screenshot and run i3lock"
version = "1.0.0"
license = "MIT OR Apache-2.0"
authors = ["Owen Walpole <owenthewizard@hotmail.com>"]
repository = "https://github.com/owenthewizard/i3lockr"
readme = "README.md"
keywords = ["i3lockr", "i3lock", "i3lock-fancy", "blur", "i3lock-color" ]
categories = ["command-line-utilities", "multimedia::images"]
edition = "2018"

[dependencies]
libc = "0.2" # should be same as xcb
num_cpus = "1"

[dependencies.imagefmt]
version = "4"
default-features = false
optional = true

[dependencies.structopt]
version = "0.2"
default-features = false

[dependencies.xcb]
version = "0.8"
features = ["randr", "shm"]

[build-dependencies]
cc = "1"

[features]
suggestions = ["structopt/suggestions"]
color = ["structopt/color"]
png = ["imagefmt/png"]
jpeg = ["imagefmt/jpeg"]
default = ["suggestions", "color", "png", "jpeg"]

[profile.release]
lto = true
codegen-units=1
